import {
  CircleDollarSign,
  CalendarClock,
  ScrollText,
  KeyRound,
  Users2,
  Wrench,
  Truck,
  LineChart,
  Wallet,
  Zap,
  Scale,
  BookOpen,
  Calculator,
  NotebookPen,
  ListOrdered,
} from "lucide-react";

export const REPORT_ROUTES = {
  bankSummary: "/reports/bank-summary",
  accountTransactions: "/reports/account-transactions",
  pnl: "/reports/pnl",
  bankImports: "/reports/bank-imports",
  bankReconciliation: "/reports/bank-reconciliation",
  manualPayments: "/reports/manual-payments",
  balanceSheet: "/reports/balance-sheet",
  cashflow: "/reports/cashflow",
  trialBalance: "/reports/trial-balance",
  generalLedger: "/reports/general-ledger",
  journalEntries: "/reports/journal-entries",
  chartOfAccounts: "/reports/chart-of-accounts",
  rentRoll: "/reports/rent-roll",
  rentLedger: "/reports/ledger",
  overdueRent: "/reports/overdue-rent",
  rentCharges: "/reports/rent-charges",
  deposits: "/reports/deposits",
  occupancy: "/reports/occupancy",
  leaseExpiry: "/reports/lease-expiry",
  tenantLedger: "/reports/tenant-ledger",
  unitFinancials: "/reports/unit-financials",
  maintenance: "/reports/maintenance",
  utilityCharges: "/reports/utility-charges",
  ownerSummary: "/reports/owner-summary",
  kpiDashboard: "/reports/kpi-dashboard",
  monthEnd: "/reports/month-end",
  supplierDirectory: "/reports/supplier-directory",
} as const;

export const REPORT_GROUPS = [
  {
    key: "banking",
    items: [
      { key: "bankSummary", href: REPORT_ROUTES.bankSummary, Icon: Wallet },
      { key: "accountTransactions", href: REPORT_ROUTES.accountTransactions, Icon: LineChart },
      { key: "pnl", href: REPORT_ROUTES.pnl, Icon: CircleDollarSign },
      { key: "bankImports", href: REPORT_ROUTES.bankImports, Icon: LineChart },
      { key: "bankReconciliation", href: REPORT_ROUTES.bankReconciliation, Icon: Wallet },
      { key: "manualPayments", href: REPORT_ROUTES.manualPayments, Icon: CircleDollarSign },
    ],
  },
  {
    key: "accounting",
    items: [
      { key: "balanceSheet", href: REPORT_ROUTES.balanceSheet, Icon: Scale },
      { key: "cashflow", href: REPORT_ROUTES.cashflow, Icon: CircleDollarSign },
      { key: "trialBalance", href: REPORT_ROUTES.trialBalance, Icon: Calculator },
      { key: "generalLedger", href: REPORT_ROUTES.generalLedger, Icon: BookOpen },
      { key: "journalEntries", href: REPORT_ROUTES.journalEntries, Icon: NotebookPen },
      { key: "chartOfAccounts", href: REPORT_ROUTES.chartOfAccounts, Icon: ListOrdered },
    ],
  },
  {
    key: "rent",
    items: [
      { key: "rentRoll", href: REPORT_ROUTES.rentRoll, Icon: ScrollText },
      { key: "rentLedger", href: REPORT_ROUTES.rentLedger, Icon: CircleDollarSign },
      { key: "overdueRent", href: REPORT_ROUTES.overdueRent, Icon: CalendarClock },
      { key: "rentCharges", href: REPORT_ROUTES.rentCharges, Icon: ScrollText },
      { key: "deposits", href: REPORT_ROUTES.deposits, Icon: ScrollText },
    ],
  },
  {
    key: "property",
    items: [
      { key: "occupancy", href: REPORT_ROUTES.occupancy, Icon: Users2 },
      { key: "leaseExpiry", href: REPORT_ROUTES.leaseExpiry, Icon: KeyRound },
      { key: "tenantLedger", href: REPORT_ROUTES.tenantLedger, Icon: Users2 },
      { key: "unitFinancials", href: REPORT_ROUTES.unitFinancials, Icon: CircleDollarSign },
      { key: "maintenance", href: REPORT_ROUTES.maintenance, Icon: Wrench },
      { key: "utilityCharges", href: REPORT_ROUTES.utilityCharges, Icon: Zap },
      { key: "ownerSummary", href: REPORT_ROUTES.ownerSummary, Icon: ScrollText },
      { key: "kpiDashboard", href: REPORT_ROUTES.kpiDashboard, Icon: LineChart },
      { key: "monthEnd", href: REPORT_ROUTES.monthEnd, Icon: CalendarClock },
      { key: "supplierDirectory", href: REPORT_ROUTES.supplierDirectory, Icon: Truck },
    ],
  },
] as const;
